/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lunch_or_net;

import lunch_or_net.acompanhamento1;
import lunch_or_net.tela_principal;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandro V Vieira
 */
public class acompanhamento3 extends javax.swing.JFrame {

    /**
     * Creates new form acompanhamento3
     */
    public acompanhamento3() {
        initComponents();
                att3.setBackground(new Color(0, 0, 0, 0));
                        btnvoltar3.setBackground(new Color(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        att3 = new javax.swing.JButton();
        btnvoltar3 = new javax.swing.JButton();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        att3.setBorder(null);
        att3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att3ActionPerformed(evt);
            }
        });
        getContentPane().add(att3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 640, 150, 40));

        btnvoltar3.setBorder(null);
        btnvoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 100, 40));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/ACOMPANHAMENTO3.0.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        setSize(new java.awt.Dimension(1370, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void att3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att3ActionPerformed
    try {
            Thread.sleep(1 * 1500 );
        } catch (InterruptedException ex) {
            Logger.getLogger(acompanhamento1.class.getName()).log(Level.SEVERE, null, ex);
        }
    acompanhamento4 a4 = new acompanhamento4();
    a4.setVisible(true);
    dispose();    dispose();    }//GEN-LAST:event_att3ActionPerformed

    private void btnvoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar3ActionPerformed
   int a = JOptionPane.showConfirmDialog(null, " Deseja voltar ao menu principal?", "Registro", JOptionPane.OK_CANCEL_OPTION);
        if (a == JOptionPane.OK_OPTION) {
             dispose();
            tela_principal ap = new tela_principal();
            ap.setVisible(true);
            dispose();
        } else {

        }
    }//GEN-LAST:event_btnvoltar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acompanhamento3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acompanhamento3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acompanhamento3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acompanhamento3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acompanhamento3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton att3;
    private javax.swing.JButton btnvoltar3;
    private javax.swing.JLabel lblfundo;
    // End of variables declaration//GEN-END:variables
}
