/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lunch_or_net;

import lunch_or_net.tela_login_senha;
import lunch_or_net.tela_principal;
import java.awt.Color;

/**
 *
 * @author Sandro V Vieira
 */
public class agredecimento extends javax.swing.JFrame {

    /**
     * Creates new form agredecimento
     */
    public agredecimento() {
        initComponents();
       //btnloga.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnloga = new javax.swing.JButton();
        btnloga1 = new javax.swing.JButton();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnloga.setBackground(new java.awt.Color(204, 204, 204));
        btnloga.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnloga.setText("LOGOUT");
        btnloga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnloga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogaActionPerformed(evt);
            }
        });
        getContentPane().add(btnloga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 680, 100, 30));

        btnloga1.setBackground(new java.awt.Color(204, 204, 204));
        btnloga1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnloga1.setText("MENU");
        btnloga1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnloga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloga1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnloga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 680, 100, 30));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/agradecimento.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        setSize(new java.awt.Dimension(1730, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogaActionPerformed
        tela_login_senha login = new tela_login_senha();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnlogaActionPerformed

    private void btnloga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloga1ActionPerformed
      tela_principal menu = new tela_principal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnloga1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agredecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agredecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agredecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agredecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agredecimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloga;
    private javax.swing.JButton btnloga1;
    private javax.swing.JLabel lblfundo;
    // End of variables declaration//GEN-END:variables
}
