/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lunch_or_net;

import lunch_or_net.tela_carrinho;
import java.awt.Color;

/**
 *
 * @author Sandro V Vieira
 */
public class tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form tela_principal
     */
    public tela_principal() {
        initComponents();

        //btnalmoco.setBackground(new Color(0, 0, 0, 0));
        // btnlanche.setBackground(new Color(0, 0, 0, 0));
        // btncarrinho.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btncarrinho = new javax.swing.JButton();
        btnalmoco = new javax.swing.JButton();
        btnlanche = new javax.swing.JButton();
        lblfundo = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        jCheckBox1.setText("jCheckBox1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Sem_titulo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        btncarrinho.setBackground(new java.awt.Color(255, 0, 0));
        btncarrinho.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btncarrinho.setText("CARRINHO");
        btncarrinho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btncarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarrinhoActionPerformed(evt);
            }
        });
        getContentPane().add(btncarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, 270, 50));

        btnalmoco.setBackground(new java.awt.Color(255, 0, 0));
        btnalmoco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnalmoco.setText("ALMOÇO");
        btnalmoco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnalmoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalmocoActionPerformed(evt);
            }
        });
        getContentPane().add(btnalmoco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 280, 50));

        btnlanche.setBackground(new java.awt.Color(255, 0, 0));
        btnlanche.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnlanche.setText("LANCHE");
        btnlanche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnlanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlancheActionPerformed(evt);
            }
        });
        getContentPane().add(btnlanche, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 280, 50));

        lblfundo.setBackground(new java.awt.Color(204, 0, 0));
        lblfundo.setForeground(new java.awt.Color(255, 0, 0));
        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/e.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        setSize(new java.awt.Dimension(1366, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarrinhoActionPerformed
        tela_carrinho carrinho = new tela_carrinho();
        carrinho.setVisible(true);
        dispose();    }//GEN-LAST:event_btncarrinhoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tela_login_senha voltar = new tela_login_senha();
        voltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnalmocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalmocoActionPerformed
        menu_almoco almoco = new menu_almoco();
        almoco.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnalmocoActionPerformed

    private void btnlancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlancheActionPerformed
        menu_lanche lanche = new menu_lanche();
        lanche.setVisible(true);
dispose();    }//GEN-LAST:event_btnlancheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalmoco;
    private javax.swing.JButton btncarrinho;
    private javax.swing.JButton btnlanche;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfundo;
    // End of variables declaration//GEN-END:variables
}
