/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lunch_or_net;

import lunch_or_net.tela_principal;
import com.sun.glass.ui.Cursor;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sandro V Vieira
 */
public class acompanhamento1 extends javax.swing.JFrame {

    /**
     * Creates new form acompanhamento1
     */
    public acompanhamento1() {
        initComponents();
        att1.setBackground(new Color(0, 0, 0, 0));
                btnvoltar1.setBackground(new Color(0, 0, 0, 0));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        att1 = new javax.swing.JButton();
        btnvoltar1 = new javax.swing.JButton();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        att1.setBorder(null);
        att1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att1ActionPerformed(evt);
            }
        });
        getContentPane().add(att1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 640, 130, 40));

        btnvoltar1.setBorder(null);
        btnvoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 100, 40));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/ACOMPANHAMENTO1.0.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        setSize(new java.awt.Dimension(1370, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void att1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att1ActionPerformed
        try {
            Thread.sleep(1 * 1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(acompanhamento1.class.getName()).log(Level.SEVERE, null, ex);
        }
        acompanhamento2 a2 = new acompanhamento2();
        a2.setVisible(true);
        dispose();

      }//GEN-LAST:event_att1ActionPerformed

    private void btnvoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar1ActionPerformed
       int a = JOptionPane.showConfirmDialog(null, " Deseja voltar ao menu principal?", "Registro", JOptionPane.OK_CANCEL_OPTION);
        if (a == JOptionPane.OK_OPTION) {
             dispose();
            tela_principal ap = new tela_principal();
            ap.setVisible(true);
            dispose();
        } else {

        }



    }//GEN-LAST:event_btnvoltar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        acompanhamento1 a1 = new acompanhamento1();
        a1.setVisible(true);

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acompanhamento1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acompanhamento1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acompanhamento1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acompanhamento1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new acompanhamento1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton att1;
    private javax.swing.JButton btnvoltar1;
    private javax.swing.JLabel lblfundo;
    // End of variables declaration//GEN-END:variables
}
