/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lunch_or_net;

import lunch_or_net.tela_login_senha;
import dao.ProdutoDAO;
import dao.UsuarioDAO;
import factory.ConnectionFactory;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javafx.scene.paint.Color.color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Produto;
import modelo.Usuario;

/**
 *
 * @author Sandro V Vieira
 */
public class tela_admin extends javax.swing.JFrame {

    Connection connection = new ConnectionFactory().getConnection();

    /**
     * Creates new form tela_admin
     */
    public tela_admin() {
        initComponents();
        btncadastro.setBackground(new Color(0, 0, 0, 0));
        btncliente.setBackground(new Color(0, 0, 0, 0));
        btnproduto.setBackground(new Color(0, 0, 0, 0));
        txttipo.setBackground(new Color(0, 0, 0, 0));
        txtvenda.setBackground(new Color(0, 0, 0, 0));
        txtdescricao.setBackground(new Color(0, 0, 0, 0));
        txtproduto.setBackground(new Color(0, 0, 0, 0));
        txtcusto1.setBackground(new Color(0, 0, 0, 0));
        txtcategoria.setBackground(new Color(0, 0, 0, 0));
        btnvoltar.setBackground(new Color(0, 0, 0, 0));
        btnvoltar.setBackground(new Color(0, 0, 0, 0));
        btnvoltar2.setBackground(new Color(0, 0, 0, 0));
        btnvoltar3.setBackground(new Color(0, 0, 0, 0));
        btnvoltar4.setBackground(new Color(0, 0, 0, 0));
        btnvoltar5.setBackground(new Color(0, 0, 0, 0));
        btnbuscar.setBackground(new Color(0, 0, 0, 0));
        btndeletar.setBackground(new Color(0, 0, 0, 0));
        btnatualizar.setBackground(new Color(0, 0, 0, 0));
        btnlimpar.setBackground(new Color(0, 0, 0, 0));
        txtusuario.setBackground(new Color(0, 0, 0, 0));
        txtid.setBackground(new Color(0, 0, 0, 0));
        txtemail.setBackground(new Color(0, 0, 0, 0));
        txtsenha.setBackground(new Color(0, 0, 0, 0));
        txtconfirmar.setBackground(new Color(0, 0, 0, 0));
        txtproduto1.setBackground(new Color(0, 0, 0, 0));
        txtid1.setBackground(new Color(0, 0, 0, 0));
        txtvenda3.setBackground(new Color(0, 0, 0, 0));
        txtdescricao1.setBackground(new Color(0, 0, 0, 0));
        txtcusto3.setBackground(new Color(0, 0, 0, 0));
        txtcategoria1.setBackground(new Color(0, 0, 0, 0));
        txttipo1.setBackground(new Color(0, 0, 0, 0));
        btnlimpar1.setBackground(new Color(0, 0, 0, 0));
        btnbuscar1.setBackground(new Color(0, 0, 0, 0));
        btndeletar1.setBackground(new Color(0, 0, 0, 0));
        btnatualizar1.setBackground(new Color(0, 0, 0, 0));
        btnclientes.setBackground(new Color(0, 0, 0, 0));
        btnprodutos.setBackground(new Color(0, 0, 0, 0));
        btnsalvar.setBackground(new Color(0, 0, 0, 0));
        //btnadmin.setBackground(new Color(0, 0, 0, 0));
        //btnadmin1.setBackground(new Color(0, 0, 0, 0));

        //tblclientes.getTableHeader().setFont(new Font("arial", Font.BOLD, 16));
        // tblclientes.getTableHeader().setOpaque(false);
        // tblclientes.getTableHeader().setBackground(new Color(0, 0, 0));
        // tblclientes.getTableHeader().setForeground(new Color(255, 0, 255));
        // tblclientes.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncadastro = new javax.swing.JButton();
        btncliente = new javax.swing.JButton();
        btnproduto = new javax.swing.JButton();
        btnprodutos = new javax.swing.JButton();
        btnclientes = new javax.swing.JButton();
        lblfundo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        CADASTRO = new javax.swing.JPanel();
        txtproduto = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        btnvoltar = new javax.swing.JButton();
        txttipo = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();
        txtvenda = new javax.swing.JFormattedTextField();
        txtcusto1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fundo1 = new javax.swing.JLabel();
        CLIENTE = new javax.swing.JPanel();
        btnatualizar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        txtconfirmar = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        btnvoltar2 = new javax.swing.JButton();
        fundo2 = new javax.swing.JLabel();
        PRODUTO = new javax.swing.JPanel();
        txtid1 = new javax.swing.JTextField();
        txtdescricao1 = new javax.swing.JTextField();
        txtcategoria1 = new javax.swing.JTextField();
        txttipo1 = new javax.swing.JTextField();
        txtproduto1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnlimpar1 = new javax.swing.JButton();
        btnatualizar1 = new javax.swing.JButton();
        btndeletar1 = new javax.swing.JButton();
        txtcusto3 = new javax.swing.JTextField();
        txtvenda3 = new javax.swing.JTextField();
        btnbuscar1 = new javax.swing.JButton();
        btnvoltar3 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        CLIENTES = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        btnvoltar4 = new javax.swing.JButton();
        lblfundooo = new javax.swing.JLabel();
        PRODUTOS = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprodutos = new javax.swing.JTable();
        btnvoltar5 = new javax.swing.JButton();
        lblfundooooo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, 40));

        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });
        getContentPane().add(btncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 230, 50));

        btnproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 230, 40));

        btnprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodutosActionPerformed(evt);
            }
        });
        getContentPane().add(btnprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 230, 50));

        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 230, 40));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/LATERALATT.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 270, 760));

        CADASTRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtproduto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtproduto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtproduto.setBorder(null);
        CADASTRO.add(txtproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 340, 30));

        txtcategoria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcategoria.setBorder(null);
        CADASTRO.add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 340, 30));

        txtdescricao.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtdescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtdescricao.setBorder(null);
        CADASTRO.add(txtdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 340, 30));

        btnvoltar.setBorder(null);
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        CADASTRO.add(btnvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 90, 40));

        txttipo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txttipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txttipo.setBorder(null);
        CADASTRO.add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 340, 30));

        btnsalvar.setBorder(null);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        CADASTRO.add(btnsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 670, 110, 50));

        txtvenda.setBorder(null);
        try {
            txtvenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtvenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtvenda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CADASTRO.add(txtvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 426, 70, 20));

        txtcusto1.setBorder(null);
        try {
            txtcusto1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcusto1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcusto1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcusto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcusto1ActionPerformed(evt);
            }
        });
        CADASTRO.add(txtcusto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 426, 70, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("R$");
        CADASTRO.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 426, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("R$");
        CADASTRO.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 426, -1, -1));

        fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/cadrprod.png"))); // NOI18N
        CADASTRO.add(fundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1120, 740));

        jTabbedPane1.addTab("tab2", CADASTRO);

        CLIENTE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnatualizar.setBorder(null);
        btnatualizar.setEnabled(false);
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });
        CLIENTE.add(btnatualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, 280, 40));

        btnbuscar.setBorder(null);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        CLIENTE.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 180, 30));

        btndeletar.setBorder(null);
        btndeletar.setEnabled(false);
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });
        CLIENTE.add(btndeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 280, 40));

        btnlimpar.setBorder(null);
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        CLIENTE.add(btnlimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 180, 30));

        txtconfirmar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtconfirmar.setBorder(null);
        CLIENTE.add(txtconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 570, 30));

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtusuario.setBorder(null);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        CLIENTE.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, 30));

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtemail.setBorder(null);
        CLIENTE.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 570, -1));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtid.setBorder(null);
        txtid.setEnabled(false);
        CLIENTE.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 570, -1));

        txtsenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsenha.setBorder(null);
        CLIENTE.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 570, 30));

        btnvoltar2.setBorder(null);
        btnvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar2ActionPerformed(evt);
            }
        });
        CLIENTE.add(btnvoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 80, 30));

        fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/buscacli.jpg"))); // NOI18N
        CLIENTE.add(fundo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1120, 740));

        jTabbedPane1.addTab("tab3", CLIENTE);

        PRODUTO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtid1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtid1.setBorder(null);
        txtid1.setEnabled(false);
        PRODUTO.add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 330, 30));

        txtdescricao1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtdescricao1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtdescricao1.setBorder(null);
        PRODUTO.add(txtdescricao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 330, 30));

        txtcategoria1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcategoria1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcategoria1.setBorder(null);
        PRODUTO.add(txtcategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 330, 30));

        txttipo1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txttipo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txttipo1.setBorder(null);
        PRODUTO.add(txttipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 330, 30));

        txtproduto1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtproduto1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtproduto1.setBorder(null);
        PRODUTO.add(txtproduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("R$");
        PRODUTO.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("R$");
        PRODUTO.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 30, 30));

        btnlimpar1.setBorder(null);
        btnlimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpar1ActionPerformed(evt);
            }
        });
        PRODUTO.add(btnlimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 170, 30));

        btnatualizar1.setBorder(null);
        btnatualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizar1ActionPerformed(evt);
            }
        });
        PRODUTO.add(btnatualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 280, 40));

        btndeletar1.setBorder(null);
        btndeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletar1ActionPerformed(evt);
            }
        });
        PRODUTO.add(btndeletar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, 280, 40));

        txtcusto3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcusto3.setBorder(null);
        PRODUTO.add(txtcusto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 70, 30));

        txtvenda3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtvenda3.setBorder(null);
        PRODUTO.add(txtvenda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 70, 30));

        btnbuscar1.setBorder(null);
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });
        PRODUTO.add(btnbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 170, 30));

        btnvoltar3.setBorder(null);
        btnvoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar3ActionPerformed(evt);
            }
        });
        PRODUTO.add(btnvoltar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 80, 30));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/buscaprod.jpg"))); // NOI18N
        PRODUTO.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 740));

        jTabbedPane1.addTab("tab1", PRODUTO);

        CLIENTES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblclientes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Usúario", "Email", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblclientes.setFocusable(false);
        tblclientes.setGridColor(new java.awt.Color(0, 0, 0));
        tblclientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblclientes.setRowHeight(30);
        tblclientes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblclientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblclientes);

        CLIENTES.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1070, 670));

        btnvoltar4.setBorder(null);
        btnvoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar4ActionPerformed(evt);
            }
        });
        CLIENTES.add(btnvoltar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 80, 30));

        lblfundooo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/buscaprod.jpg"))); // NOI18N
        CLIENTES.add(lblfundooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 740));

        jTabbedPane1.addTab("tab4", CLIENTES);

        PRODUTOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblprodutos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Produto", "Descrição", "Preço/Custo", "Preço/Venda", "Categoria", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblprodutos.setFocusable(false);
        tblprodutos.setGridColor(new java.awt.Color(0, 0, 0));
        tblprodutos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblprodutos.setMaximumSize(new java.awt.Dimension(2147483647, 1500));
        tblprodutos.setPreferredSize(new java.awt.Dimension(300, 1500));
        tblprodutos.setRowHeight(30);
        tblprodutos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblprodutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblprodutos);

        PRODUTOS.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1070, 670));

        btnvoltar5.setBorder(null);
        btnvoltar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar5ActionPerformed(evt);
            }
        });
        PRODUTOS.add(btnvoltar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 70, 30));

        lblfundooooo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/buscaprod.jpg"))); // NOI18N
        PRODUTOS.add(lblfundooooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1140, 760));

        jTabbedPane1.addTab("tab5", PRODUTOS);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -30, 1190, 990));

        setSize(new java.awt.Dimension(1370, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastroActionPerformed
jTabbedPane1.setSelectedIndex(0);    }//GEN-LAST:event_btncadastroActionPerformed

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
jTabbedPane1.setSelectedIndex(1);    }//GEN-LAST:event_btnclienteActionPerformed

    private void btnprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodutoActionPerformed
jTabbedPane1.setSelectedIndex(2);    }//GEN-LAST:event_btnprodutoActionPerformed

    public void ativaBotao() {
        btnatualizar1.setEnabled(true);
        btndeletar1.setEnabled(true);

    }

    public void ativaBotao2() {
        btnatualizar.setEnabled(true);
        btndeletar.setEnabled(true);

    }

    public void desativaBotao() {
        btnatualizar1.setEnabled(false);
        btndeletar1.setEnabled(false);

    }

    public void desativaBotao2() {
        btnatualizar.setEnabled(false);
        btndeletar.setEnabled(false);

    }

    public void LimpaCampos() {
        txtid.setText("");
        txtemail.setText("");
        txtsenha.setText("");
        txtconfirmar.setText("");
        txtusuario.setText("");

    }

    public void LimpaCampos1() {
        txtid1.setText("");
        txtdescricao1.setText("");
        txtcusto3.setText("");
        txtvenda3.setText("");
        txtcategoria1.setText("");
        txttipo1.setText("");
        txtproduto1.setText("");

    }
    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        tela_login_senha login = new tela_login_senha();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // instanciando a classe Usuario do pacote modelo e criando seu objeto usuarios
        Produto produtos = new Produto();
        produtos.setProduto(txtproduto.getText());
        produtos.setDescricao(txtdescricao.getText());
        produtos.setPreçocusto(txtcusto1.getText());
        produtos.setPreçovenda(txtvenda.getText());
        produtos.setCategoria(txtcategoria.getText());
        produtos.setTipo(txttipo.getText());

        // fazendo a validação dos dados
        if ((txtproduto.getText().isEmpty()) || (txtdescricao.getText().isEmpty()) || (txtcategoria.getText().isEmpty()) || (txttipo.getText().isEmpty()) || (txtcusto1.getText().isEmpty()) || (txtvenda.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else if (txtcusto1.getText().equals("  .  ") || txtvenda.getText().equals("  .  ")) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            ProdutoDAO dao = new ProdutoDAO();
            dao.adiciona(produtos);
            JOptionPane.showMessageDialog(null, "Produto '" + txtproduto.getText() + "' cadastrado com sucesso!");
            //txtproduto.setText("");
            //txtdescricao.setText("");
            //txtcusto1.setText("");
            //txtvenda.setText("");
            //txtcategoria.setText("");
            // txttipo.setText("");
        }

    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtcusto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcusto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcusto1ActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        // para evitar erro siga as instruções do vídeo
        if (txtusuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o usúario");
        } else if (!txtsenha.getText().equals(txtconfirmar.getText())) {
            JOptionPane.showMessageDialog(null, "As senhas não coincidem! ");
            txtsenha.setText("");
            txtconfirmar.setText("");
        } else {

            Usuario usuarios = new Usuario();
            usuarios.setEmail(txtemail.getText());
            usuarios.setSenha(txtsenha.getText());
            usuarios.setConfirmar(txtconfirmar.getText());
            usuarios.setNome(txtusuario.getText());
            UsuarioDAO dao = new UsuarioDAO();
            dao.update(usuarios);
            txtemail.setText("");
            txtsenha.setText("");
            txtconfirmar.setText("");
            txtid.setText("");
            desativaBotao2();

        }
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        ativaBotao2();
        try {
            Usuario usuarios = new Usuario();
            usuarios.setNome(txtusuario.getText());
            UsuarioDAO dao = new UsuarioDAO();
            dao.select(usuarios);
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select * from cadastro where usuario = ? ";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, txtusuario.getText());
            ResultSet rs = stmt.executeQuery();

            if (txtusuario.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Usúario!");
            } else if (rs.next()) {
                txtid.setText(usuarios.getId());
                txtemail.setText(usuarios.getEmail());
                txtsenha.setText(usuarios.getSenha());
                txtconfirmar.setText(usuarios.getConfirmar());
                ;
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não encontrado");
                LimpaCampos();
                desativaBotao2();

            }
            rs.close();
            connection.close();
        } catch (Exception e) {

        }
            }//GEN-LAST:event_btnbuscarActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed

        if (txtusuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o usúario!");

        } else {
            Usuario usuarios = new Usuario();
            usuarios.setNome(txtusuario.getText());
            UsuarioDAO dao = new UsuarioDAO();
            dao.delete(usuarios);
            txtid.setText("");
            txtemail.setText("");
            txtsenha.setText("");
            txtconfirmar.setText("");
            desativaBotao2();
        }

    }//GEN-LAST:event_btndeletarActionPerformed

    private void btnatualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizar1ActionPerformed

        if (txtproduto1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o produto!");

        } else {

            Produto produto = new Produto();
            produto.setDescricao(txtdescricao1.getText());
            produto.setPreçocusto(txtcusto3.getText());
            produto.setPreçovenda(txtvenda3.getText());
            produto.setCategoria(txtcategoria1.getText());
            produto.setTipo(txttipo1.getText());
            produto.setProduto(txtproduto1.getText());
            ProdutoDAO dao = new ProdutoDAO();
            dao.update(produto);

            txtdescricao1.setText("");
            txtcusto3.setText("");
            txtvenda3.setText("");
            txtid1.setText("");
            txtcategoria1.setText("");
            txttipo1.setText("");
            desativaBotao();

            }//GEN-LAST:event_btnatualizar1ActionPerformed
    }
    private void btndeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletar1ActionPerformed
        if (txtproduto1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o produto!");

        } else {
            Produto produto = new Produto();
            produto.setProduto(txtproduto1.getText());
            ProdutoDAO dao = new ProdutoDAO();
            dao.delete(produto);

            txtid1.setText("");
            txtdescricao1.setText("");
            txtcusto3.setText("");
            txtvenda3.setText("");
            txtcategoria1.setText("");
            txttipo1.setText("");
            txtproduto1.setText("");
            desativaBotao();

        }    }//GEN-LAST:event_btndeletar1ActionPerformed

    private void btnlimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpar1ActionPerformed
        desativaBotao();
        txtid1.setText("");
        txtproduto1.setText("");
        txttipo1.setText("");
        txtcusto3.setText("");
        txtcategoria1.setText("");
        txtvenda3.setText("");
      txtdescricao1.setText("");    }//GEN-LAST:event_btnlimpar1ActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        txtid.setText("");
        txtusuario.setText("");
        txtemail.setText("");
        txtsenha.setText("");
        txtconfirmar.setText("");
        desativaBotao2();
          }//GEN-LAST:event_btnlimparActionPerformed

    private void btnprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodutosActionPerformed
        try {
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select *from cprodutos";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tblprodutos.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("produto"), rs.getString("descricao"), rs.getString("preçocusto"), rs.getString("preçovenda"), rs.getString("categoria"), rs.getString("tipo")});
            }

            rs.close();
            connection.close();

        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        jTabbedPane1.setSelectedIndex(4);     }//GEN-LAST:event_btnprodutosActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        try {
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select *from cadastro";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tblclientes.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("usuario"), rs.getString("email"), rs.getString("senha")});
            }

            rs.close();
            connection.close();

        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        jTabbedPane1.setSelectedIndex(3);    }//GEN-LAST:event_btnclientesActionPerformed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        ativaBotao();
        try {
            Produto produtos = new Produto();
            produtos.setProduto(txtproduto1.getText());
            ProdutoDAO dao = new ProdutoDAO();
            dao.select(produtos);
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select * from cprodutos where produto = ? ";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, txtproduto1.getText());
            ResultSet rs = stmt.executeQuery();

            if (txtproduto1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Produto");
            } else if (rs.next()) {
                txtid1.setText(produtos.getId());
                txtdescricao1.setText(produtos.getDescricao());
                txtcusto3.setText(produtos.getPreçocusto());
                txtvenda3.setText(produtos.getPreçovenda());
                txtcategoria1.setText(produtos.getCategoria());
                txttipo1.setText(produtos.getTipo());
            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
                LimpaCampos1();
                desativaBotao();

            }
            rs.close();
            connection.close();
        } catch (Exception e) {


            /*if (txtproduto1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Produto!");
        } else {
            Produto produto = new Produto();
            produto.setProduto(txtproduto1.getText());
            ProdutoDAO dao = new ProdutoDAO();
            dao.select(produto);
            txtid1.setText(produto.getId());
            txtdescricao1.setText(produto.getDescricao());
            txtcusto3.setText(produto.getPreçocusto());
            txtvenda3.setText(produto.getPreçovenda());
            txtcategoria1.setText(produto.getCategoria());
            txttipo1.setText(produto.getTipo());
        }
             */
        }
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void btnvoltar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar5ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnvoltar5ActionPerformed

    private void btnvoltar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar4ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnvoltar4ActionPerformed

    private void btnvoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar3ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnvoltar3ActionPerformed

    private void btnvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar2ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnvoltar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CADASTRO;
    private javax.swing.JPanel CLIENTE;
    private javax.swing.JPanel CLIENTES;
    private javax.swing.JPanel PRODUTO;
    private javax.swing.JPanel PRODUTOS;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btnatualizar1;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btncadastro;
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btndeletar1;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnlimpar1;
    private javax.swing.JButton btnproduto;
    private javax.swing.JButton btnprodutos;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JButton btnvoltar2;
    private javax.swing.JButton btnvoltar3;
    private javax.swing.JButton btnvoltar4;
    private javax.swing.JButton btnvoltar5;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundo1;
    private javax.swing.JLabel fundo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lblfundooo;
    private javax.swing.JLabel lblfundooooo;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTable tblprodutos;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcategoria1;
    private javax.swing.JTextField txtconfirmar;
    private javax.swing.JFormattedTextField txtcusto1;
    private javax.swing.JTextField txtcusto3;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtdescricao1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtproduto;
    private javax.swing.JTextField txtproduto1;
    private javax.swing.JTextField txtsenha;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txttipo1;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JFormattedTextField txtvenda;
    private javax.swing.JTextField txtvenda3;
    // End of variables declaration//GEN-END:variables
}
