/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lunch_or_net;

import dao.CartaoDAO;
import dao.EnderecoDAO;
import dao.ProdutoDAO;
import factory.ConnectionFactory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cartao;
import modelo.Endereco;
import modelo.Produto;

/**
 *
 * @author Sandro V Vieira
 */
public class tela_carrinho extends javax.swing.JFrame {

    /**
     * Creates new form tela_carrinho
     */
    public tela_carrinho() {
        initComponents();

        btnresumo1.setBackground(new Color(0, 0, 0, 0));
        btnpagamento1.setBackground(new Color(0, 0, 0, 0));
        btnentrega1.setBackground(new Color(0, 0, 0, 0));
        txtvalor.setBackground(new Color(0, 0, 0, 0));
        txtvalor2.setBackground(new Color(0, 0, 0, 0));
        txtvalor3.setBackground(new Color(0, 0, 0, 0));
        btnpagarpix.setBackground(new Color(0, 0, 0, 0));
        btnvoltar1.setBackground(new Color(0, 0, 0, 0));
        btnvoltar2.setBackground(new Color(0, 0, 0, 0));
        btnvoltar3.setBackground(new Color(0, 0, 0, 0));
        cbuf.setBackground(new Color(0, 0, 0, 0));
        txtusuario.setBackground(new Color(0, 0, 0, 0));
        txtnome.setBackground(new Color(0, 0, 0, 0));
        txtcep.setBackground(new Color(0, 0, 0, 0));
        txtendereco.setBackground(new Color(0, 0, 0, 0));
        txtnumero.setBackground(new Color(0, 0, 0, 0));
        txtcomplemento.setBackground(new Color(0, 0, 0, 0));
        txtbairro.setBackground(new Color(0, 0, 0, 0));
        txtcidade.setBackground(new Color(0, 0, 0, 0));
        txtbandeira.setBackground(new Color(0, 0, 0, 0));
        txtusuario1.setBackground(new Color(0, 0, 0, 0));
        txtnome1.setBackground(new Color(0, 0, 0, 0));
        txtnumero1.setBackground(new Color(0, 0, 0, 0));
        txtvalidade.setBackground(new Color(0, 0, 0, 0));
        txtcvv.setBackground(new Color(0, 0, 0, 0));
        btnvisa.setBackground(new Color(0, 0, 0, 0));
        brnmaster.setBackground(new Color(0, 0, 0, 0));
        btnhiper.setBackground(new Color(0, 0, 0, 0));
        btnelo.setBackground(new Color(0, 0, 0, 0));
        btnsalvar.setBackground(new Color(0, 0, 0, 0));
        btnpagarcartao.setBackground(new Color(0, 0, 0, 0));
        btncancelar.setBackground(new Color(0, 0, 0, 0));
        btnpagarcartao.setBackground(new Color(0, 0, 0, 0));
        btnconfirmar.setBackground(new Color(0, 0, 0, 0));
        btnconfirma.setBackground(new Color(0, 0, 0, 0));

        try {
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select *from cprodutos where quantidade > 0";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tblcarrinho.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("produto"), rs.getString("quantidade"), rs.getString("categoria"), rs.getString("precoatt")});
            }

            rs.close();
            connection.close();

        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        int numrow = tblcarrinho.getRowCount();
        float tot = 0;
        float desc = 0;
        float fim = 0;

        for (int i = 0; i < numrow; i++) {
            float val = Float.valueOf(tblcarrinho.getValueAt(i, 3).toString());
            tot = tot + val;
        }
        desc = (tot * 10) / 100;
        fim = tot - desc;

        DecimalFormat formatador = new DecimalFormat("0.00");
        formatador.format(tot);

        txtvalor.setText(Float.toString(tot).format("%.2f", tot));
        txtvalor2.setText(Float.toString(fim).format("%.2f", fim));
        txtvalor3.setText(Float.toString(fim).format("%.2f", fim));

        System.out.println(tot);
        System.out.println(fim);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpagamento1 = new javax.swing.JButton();
        btnentrega1 = new javax.swing.JButton();
        btnresumo1 = new javax.swing.JButton();
        lbllateral = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        RESUMO = new javax.swing.JPanel();
        txtvalor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtvalor2 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcarrinho = new javax.swing.JTable();
        btnvoltar1 = new javax.swing.JButton();
        btnconfirmar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        fundoentregaa = new javax.swing.JLabel();
        ENTREGA = new javax.swing.JPanel();
        txtcidade = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtcomplemento = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        cbuf = new javax.swing.JComboBox<>();
        txtcep = new javax.swing.JFormattedTextField();
        txtnumero = new javax.swing.JFormattedTextField();
        btnconfirma = new javax.swing.JButton();
        btnvoltar2 = new javax.swing.JButton();
        resumofundoo = new javax.swing.JLabel();
        PAGAMENTO = new javax.swing.JPanel();
        txtvalor3 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnpagarpix = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        txtusuario1 = new javax.swing.JTextField();
        txtnome1 = new javax.swing.JTextField();
        txtbandeira = new javax.swing.JTextField();
        txtcvv = new javax.swing.JFormattedTextField();
        txtnumero1 = new javax.swing.JFormattedTextField();
        txtvalidade = new javax.swing.JFormattedTextField();
        brnmaster = new javax.swing.JButton();
        btnhiper = new javax.swing.JButton();
        btnelo = new javax.swing.JButton();
        btnvisa = new javax.swing.JButton();
        btnpagarcartao = new javax.swing.JButton();
        btnvoltar3 = new javax.swing.JButton();
        pagamentofundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpagamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagamento1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnpagamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 50));

        btnentrega1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrega1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 230, 50));

        btnresumo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresumo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresumo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 230, 50));

        lbllateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/testa ae.png"))); // NOI18N
        getContentPane().add(lbllateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, 760));

        RESUMO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtvalor.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtvalor.setText("0");
        txtvalor.setBorder(null);
        txtvalor.setEnabled(false);
        RESUMO.add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 90, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("R$");
        RESUMO.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 30, 40));

        txtvalor2.setBorder(null);
        txtvalor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtvalor2.setText("0");
        txtvalor2.setEnabled(false);
        txtvalor2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RESUMO.add(txtvalor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 610, 90, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("R$");
        RESUMO.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 30, 40));

        tblcarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Categoria", "Valor "
            }
        ));
        tblcarrinho.setEnabled(false);
        tblcarrinho.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblcarrinho.setRowHeight(30);
        tblcarrinho.setSurrendersFocusOnKeystroke(true);
        tblcarrinho.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblcarrinho);

        RESUMO.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 870, 440));

        btnvoltar1.setBorder(null);
        btnvoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar1ActionPerformed(evt);
            }
        });
        RESUMO.add(btnvoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 100, 30));

        btnconfirmar.setBorder(null);
        btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarActionPerformed(evt);
            }
        });
        RESUMO.add(btnconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 650, 120, 30));

        btncancelar.setBorder(null);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        RESUMO.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 690, 110, 30));

        fundoentregaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/BG-FINAL.jpg"))); // NOI18N
        RESUMO.add(fundoentregaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 740));

        jTabbedPane1.addTab("tab1", RESUMO);

        ENTREGA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcidade.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcidade.setBorder(null);
        txtcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidadeActionPerformed(evt);
            }
        });
        ENTREGA.add(txtcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 160, 20));

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtusuario.setBorder(null);
        ENTREGA.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 360, 20));

        txtcomplemento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcomplemento.setBorder(null);
        ENTREGA.add(txtcomplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 360, 30));

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnome.setBorder(null);
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        ENTREGA.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 360, 30));

        txtbairro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtbairro.setBorder(null);
        txtbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbairroActionPerformed(evt);
            }
        });
        ENTREGA.add(txtbairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 150, 20));

        txtendereco.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtendereco.setBorder(null);
        ENTREGA.add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 150, 20));

        cbuf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MS", "MT", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        cbuf.setBorder(null);
        cbuf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ENTREGA.add(cbuf, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 60, 20));

        txtcep.setBorder(null);
        txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##,###,###"))));
        txtcep.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ENTREGA.add(txtcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 150, 20));

        txtnumero.setBorder(null);
        txtnumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnumero.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ENTREGA.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 30, 20));

        btnconfirma.setBorder(null);
        btnconfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmaActionPerformed(evt);
            }
        });
        ENTREGA.add(btnconfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 680, 120, 40));

        btnvoltar2.setBorder(null);
        btnvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar2ActionPerformed(evt);
            }
        });
        ENTREGA.add(btnvoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 90, 30));

        resumofundoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/ENDRÇ.jpg"))); // NOI18N
        ENTREGA.add(resumofundoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1120, 740));

        jTabbedPane1.addTab("tab2", ENTREGA);

        PAGAMENTO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtvalor3.setBorder(null);
        txtvalor3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtvalor3.setText("0");
        txtvalor3.setEnabled(false);
        txtvalor3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PAGAMENTO.add(txtvalor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 488, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("R$");
        PAGAMENTO.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 488, -1, 20));

        btnpagarpix.setBorder(null);
        btnpagarpix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarpixActionPerformed(evt);
            }
        });
        PAGAMENTO.add(btnpagarpix, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 110, 40));

        btnsalvar.setBorder(null);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        PAGAMENTO.add(btnsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 670, 120, 40));

        txtusuario1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtusuario1.setBorder(null);
        PAGAMENTO.add(txtusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 320, 30));

        txtnome1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnome1.setBorder(null);
        PAGAMENTO.add(txtnome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 320, 30));

        txtbandeira.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtbandeira.setBorder(null);
        txtbandeira.setEnabled(false);
        PAGAMENTO.add(txtbandeira, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 320, 30));

        txtcvv.setBorder(null);
        txtcvv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        txtcvv.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcvvActionPerformed(evt);
            }
        });
        PAGAMENTO.add(txtcvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 140, 30));

        txtnumero1.setBorder(null);
        txtnumero1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####,####,####,####"))));
        txtnumero1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PAGAMENTO.add(txtnumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 320, 30));

        txtvalidade.setBorder(null);
        txtvalidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtvalidade.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PAGAMENTO.add(txtvalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 130, 30));

        brnmaster.setBorder(null);
        brnmaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnmasterActionPerformed(evt);
            }
        });
        PAGAMENTO.add(brnmaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 90));

        btnhiper.setBorder(null);
        btnhiper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhiperActionPerformed(evt);
            }
        });
        PAGAMENTO.add(btnhiper, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 80, 90));

        btnelo.setBorder(null);
        btnelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneloActionPerformed(evt);
            }
        });
        PAGAMENTO.add(btnelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 50, 90));

        btnvisa.setBorder(null);
        btnvisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvisaActionPerformed(evt);
            }
        });
        PAGAMENTO.add(btnvisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 90, 90));

        btnpagarcartao.setBorder(null);
        btnpagarcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarcartaoActionPerformed(evt);
            }
        });
        PAGAMENTO.add(btnpagarcartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 120, 40));

        btnvoltar3.setBorder(null);
        btnvoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar3ActionPerformed(evt);
            }
        });
        PAGAMENTO.add(btnvoltar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 90, 40));

        pagamentofundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS2/MERCADOPAGO.jpg"))); // NOI18N
        PAGAMENTO.add(pagamentofundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1120, 740));

        jTabbedPane1.addTab("tab3", PAGAMENTO);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -30, 1100, 760));

        setSize(new java.awt.Dimension(1370, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public void inicia() throws InterruptedException {
        acompanhamento1 a1 = new acompanhamento1();
        a1.setVisible(true);
        Thread.sleep(3 * 1000);
        //a1.dispose();
        acompanhamento2 a2 = new acompanhamento2();
        a2.setVisible(true);
        Thread.sleep(5 * 1000);
        //a2.dispose();
        acompanhamento3 a3 = new acompanhamento3();
        a3.setVisible(true);
        Thread.sleep(7 * 1000);
        //a3.dispose();
        acompanhamento4 a4 = new acompanhamento4();
        a4.setVisible(true);
        Thread.sleep(10 * 1000);
        //a4.dispose();
        acompanhamento5 a5 = new acompanhamento5();
        a5.setVisible(true);
        Thread.sleep(5 * 1000);
        agredecimento a7 = new agredecimento();
        a7.setVisible(true);
        Thread.sleep(5 * 1000);
        a7.setVisible(false);
        tela_principal a6 = new tela_principal();
        a6.setVisible(true);
    }
    private void btnpagamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagamento1ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnpagamento1ActionPerformed

    private void btnentrega1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrega1ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnentrega1ActionPerformed

    private void btnresumo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresumo1ActionPerformed
jTabbedPane1.setSelectedIndex(2);    }//GEN-LAST:event_btnresumo1ActionPerformed

    private void btnvoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar1ActionPerformed
        tela_principal tela = new tela_principal();
        tela.setVisible(true);
        dispose();
     }//GEN-LAST:event_btnvoltar1ActionPerformed

    private void btnpagarpixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarpixActionPerformed
        try {
            Produto produto = new Produto();

            Connection connection = new ConnectionFactory().getConnection();
            String sql = "update cprodutos set quantidade = 0;";
            PreparedStatement stmt = connection.prepareStatement(sql);

            stmt.execute();
            stmt.close();
            connection.close();

            // JOptionPane.showMessageDialog(null, " Pagamento autorizado!");
            stmt.close();
            connection.close();

            //limpa os campos
        } catch (SQLException e1) {

            e1.printStackTrace();

        }
        int a = JOptionPane.showConfirmDialog(null, " Pagamento autorizado!\n deseja acompanhar seu pedido?", "Registro", JOptionPane.OK_CANCEL_OPTION);
        if (a == JOptionPane.OK_OPTION) {
            dispose();
            acompanhamento1 a1 = new acompanhamento1();
            a1.setVisible(true);
            dispose();
        } else {

        }


    }//GEN-LAST:event_btnpagarpixActionPerformed

    private void txtcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidadeActionPerformed

    private void txtbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbairroActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void btnconfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmaActionPerformed
        if ((txtusuario.getText().isEmpty()) || (txtnome.getText().isEmpty()) || (txtcep.getText().isEmpty()) || (txtendereco.getText().isEmpty()) || (txtnumero.getText().isEmpty()) || (txtcomplemento.getText().isEmpty()) || (txtbairro.getText().isEmpty()) || (txtcidade.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {

            // instanciando a classe Usuario do pacote modelo e criando seu objeto usuarios
            Endereco endereco = new Endereco();
            endereco.setUsuario(txtusuario.getText());
            endereco.setNome(txtnome.getText());
            endereco.setCep(txtcep.getText());
            endereco.setEnrececo(txtendereco.getText());
            endereco.setNumero(txtnumero.getText());
            endereco.setComplemento(txtcomplemento.getText());
            endereco.setBairro(txtbairro.getText());
            endereco.setCidade(txtcidade.getText());
            endereco.setUf(String.valueOf(cbuf.getSelectedItem()));

            // fazendo a validação dos dados
            //if ((txtproduto.getText().isEmpty()) || (txtdescricao.getText().isEmpty()) || (txtcategoria.getText().isEmpty()) || (txttipo.getText().isEmpty()) || (txtcusto1.getText().isEmpty()) || (txtvenda.getText().isEmpty())) {
            //     JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            //} else if (txtcusto1.getText().equals("  .  ") || txtvenda.getText().equals("  .  ")) {
            //    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            //} else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            EnderecoDAO dao = new EnderecoDAO();
            dao.adiciona(endereco);
            JOptionPane.showMessageDialog(null, "cadastrado com sucesso!");
            //txtproduto.setText("");
            //txtdescricao.setText("");
            //txtcusto1.setText("");
            //txtvenda.setText("");
            //txtcategoria.setText("");
            // txttipo.setText("");
            // }
            jTabbedPane1.setSelectedIndex(2);
        }

    }//GEN-LAST:event_btnconfirmaActionPerformed

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnconfirmarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        int a = JOptionPane.showConfirmDialog(null, " deseja cancelar seu pedido?", "Registro", JOptionPane.OK_CANCEL_OPTION);
        if (a == JOptionPane.OK_OPTION) {
            JOptionPane.showMessageDialog(null, "Seu pedido foi cancelado!");
            txtvalor.setText("0,00");
            txtvalor2.setText("0,00");
            txtvalor3.setText("0,00");
            tela_principal tp = new tela_principal();
            tp.setVisible(true);
            dispose();
            try {
                Produto produto = new Produto();

                Connection connection = new ConnectionFactory().getConnection();
                String sql = "update cprodutos set quantidade = 0;";
                PreparedStatement stmt = connection.prepareStatement(sql);

                stmt.execute();
                stmt.close();
                connection.close();

                stmt.close();
                connection.close();

                //limpa os campos
            } catch (SQLException e1) {

                e1.printStackTrace();

            }
            try {
                Connection connection = new ConnectionFactory().getConnection();
                String sql = "select *from cprodutos where quantidade > 0";
                PreparedStatement stmt = connection.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                DefaultTableModel modelo = (DefaultTableModel) tblcarrinho.getModel();
                modelo.setNumRows(0);

                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getString("produto"), rs.getString("quantidade"), rs.getString("categoria"), rs.getString("precoatt")});
                }

                rs.close();
                connection.close();

            } catch (SQLException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }

        } else {

       }    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        if ((txtusuario1.getText().isEmpty()) || (txtnome1.getText().isEmpty()) || (txtnumero1.getText().isEmpty()) || (txtvalidade.getText().isEmpty()) || (txtcvv.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
            // instanciando a classe Usuario do pacote modelo e criando seu objeto usuarios
            Cartao cartao = new Cartao();
            cartao.setBandeira(txtbandeira.getText());
            cartao.setUsuario(txtusuario1.getText());
            cartao.setNome(txtnome1.getText());
            cartao.setNumero(txtnumero1.getText());
            cartao.setValidade(txtvalidade.getText());
            cartao.setCvv(txtcvv.getText());

            // fazendo a validação dos dados
            //if ((txtproduto.getText().isEmpty()) || (txtdescricao.getText().isEmpty()) || (txtcategoria.getText().isEmpty()) || (txttipo.getText().isEmpty()) || (txtcusto1.getText().isEmpty()) || (txtvenda.getText().isEmpty())) {
            //     JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            //} else if (txtcusto1.getText().equals("  .  ") || txtvenda.getText().equals("  .  ")) {
            //    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            //} else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            CartaoDAO dao = new CartaoDAO();
            dao.adiciona(cartao);
            JOptionPane.showMessageDialog(null, "Cartão cadastrado com sucesso!");
            //txtproduto.setText("");
            //txtdescricao.setText("");
            //txtcusto1.setText("");
            //txtvenda.setText("");
            //txtcategoria.setText("");
            // txttipo.setText("");
        }
            }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnhiperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhiperActionPerformed
        txtbandeira.setText("Hiper card");
    }//GEN-LAST:event_btnhiperActionPerformed

    private void btnvisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvisaActionPerformed
        txtbandeira.setText("Visa");
    }//GEN-LAST:event_btnvisaActionPerformed

    private void brnmasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnmasterActionPerformed
        txtbandeira.setText("Master Card");
    }//GEN-LAST:event_brnmasterActionPerformed

    private void btneloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneloActionPerformed
        txtbandeira.setText("Elo");
    }//GEN-LAST:event_btneloActionPerformed

    private void btnpagarcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarcartaoActionPerformed
        try {
            Produto produto = new Produto();

            Connection connection = new ConnectionFactory().getConnection();
            String sql = "update cprodutos set quantidade = 0;";
            PreparedStatement stmt = connection.prepareStatement(sql);

            stmt.execute();
            stmt.close();
            connection.close();

            //JOptionPane.showMessageDialog(null, " Pagamento autorizado!");
            stmt.close();
            connection.close();

            //limpa os campos
        } catch (SQLException e1) {

            e1.printStackTrace();

        }
        int a = JOptionPane.showConfirmDialog(null, " Pagamento autorizado!\n deseja acompanhar seu pedido?", "Registro", JOptionPane.OK_CANCEL_OPTION);
        if (a == JOptionPane.OK_OPTION) {
            dispose();
            acompanhamento1 a1 = new acompanhamento1();
            a1.setVisible(true);
            dispose();

        } else {

        }

    }//GEN-LAST:event_btnpagarcartaoActionPerformed

    private void btnvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar2ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnvoltar2ActionPerformed

    private void btnvoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar3ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnvoltar3ActionPerformed

    private void txtcvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcvvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_carrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ENTREGA;
    private javax.swing.JPanel PAGAMENTO;
    private javax.swing.JPanel RESUMO;
    private javax.swing.JButton brnmaster;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconfirma;
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JButton btnelo;
    private javax.swing.JButton btnentrega1;
    private javax.swing.JButton btnhiper;
    private javax.swing.JButton btnpagamento1;
    private javax.swing.JButton btnpagarcartao;
    private javax.swing.JButton btnpagarpix;
    private javax.swing.JButton btnresumo1;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnvisa;
    private javax.swing.JButton btnvoltar1;
    private javax.swing.JButton btnvoltar2;
    private javax.swing.JButton btnvoltar3;
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JLabel fundoentregaa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbllateral;
    private javax.swing.JLabel pagamentofundo;
    private javax.swing.JLabel resumofundoo;
    private javax.swing.JTable tblcarrinho;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtbandeira;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JFormattedTextField txtcvv;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnome1;
    private javax.swing.JFormattedTextField txtnumero;
    private javax.swing.JFormattedTextField txtnumero1;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JTextField txtusuario1;
    private javax.swing.JFormattedTextField txtvalidade;
    private javax.swing.JTextField txtvalor;
    private javax.swing.JFormattedTextField txtvalor2;
    private javax.swing.JFormattedTextField txtvalor3;
    // End of variables declaration//GEN-END:variables
}
