/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lunch_or_net;

import lunch_or_net.tela_principal;
import lunch_or_net.tela_cadastro;
import factory.ConnectionFactory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Sandro V Vieira
 */
public class tela_login_senha extends javax.swing.JFrame {

    /**
     * Creates new form tela_login_senha
     */
    public tela_login_senha() {
        initComponents();
        txtusuario.setBackground(new Color(0, 0, 0, 0));
        txtsenha.setBackground(new Color(0, 0, 0, 0));
        btnentrar.setBackground(new Color(0, 0, 0, 0));
        btncadastrar.setBackground(new Color(0, 0, 0, 0));
        btnsair.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsair = new javax.swing.JButton();
        btnentrar = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        lblfundo = new javax.swing.JLabel();
        lblfundoo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsair.setBackground(new java.awt.Color(204, 204, 204));
        btnsair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsair.setBorder(null);
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 350, 33));

        btnentrar.setBackground(new java.awt.Color(255, 0, 0));
        btnentrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setBorder(null);
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 350, 30));

        btncadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btncadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncadastrar.setForeground(new java.awt.Color(255, 0, 0));
        btncadastrar.setBorder(null);
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 350, 33));

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtusuario.setBorder(null);
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 330, 20));

        txtsenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsenha.setBorder(null);
        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 330, 20));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Login_bonito.png"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        lblfundoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/AMAMOS_A_IMAGEM_DO_AGEO.png"))); // NOI18N
        getContentPane().add(lblfundoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        setSize(new java.awt.Dimension(1366, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        try {
            Connection connection = new ConnectionFactory().getConnection();    //puxar conexão co m banco de dados
            String sql = "select * from cadastro where usuario = ? and senha = ?";    //comandos no mysql
            PreparedStatement stmt = connection.prepareCall(sql);   //preparação dos dados para enviar para a conexao, devido a variavel sql
            stmt.setString(1, txtusuario.getText());   //quais as informações vou mandar? 1 = campo1(usuario)
            stmt.setString(2, new String(txtsenha.getPassword()));    //quais as informações vou mandar? 2 = campo2(senha)
            ResultSet rs = stmt.executeQuery();    //existe a informação no banco ou não?
            // executeQuery = executa a conulta no banco
            //stmt prepara a informação
            if (rs.next()) {  //se tiver a informação no banco
                tela_principal tela = new tela_principal();
                tela.setVisible(true);
                dispose();
            } else if ((txtusuario.getText().isEmpty()) || (txtsenha.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            } else if (txtusuario.getText().equalsIgnoreCase("admin") && txtsenha.getText().equals("admin")) {
                tela_admin admin = new tela_admin();   //chamar e criar variavel tela
                admin.setVisible(true);    //ativar variavel tela
                dispose(); //fechar tela anterior
            } else {

                JOptionPane.showMessageDialog(null, "Usúário ou senha inválidos!\nEfetue o cadastro ou verifique novamente suas informações!");
            }
            txtsenha.setText("");
            stmt.close();
            connection.close();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnentrarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnsairActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed

        tela_cadastro cadastro = new tela_cadastro();
        cadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_login_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_login_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_login_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_login_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new tela_login_senha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnsair;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lblfundoo;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
